### PR TITLE
When the app's image is present, it is displayed above the introductory text and the current version.

### PR DESCRIPTION
**Pull request by DevDelleDonne**

### CODE REVIEW

**Review by 1998code — APPROVED** [review]
'APPROVE' performed by Xcode.

**Comment by 1998code** [comment]
Thank you @DevDelleDonne :)

**Comment by 1998code** [comment]
Adjusted some coding and reduced the icon size to ensure it looks good, even on a small device.
Release in 3.9.6.

simulator_screenshot_9A86BB3A-A977-4FF4-957C-A3A87EE90A0C

**Comment by DevDelleDonne** [comment]
Great!

**Pull request merged**
